# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luke', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(default=b'Blog Post', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(default=b'Blog Post', max_length=200),
        ),
    ]
